-module(nklib_mime).
-export([ext/1, mime/1]).
-define(MIMES, #{<<"application/vnd.lotus-notes">> => <<"nsf">>,
  <<"model/x3d+xml">> => <<"x3dz">>,<<"application/rsd+xml">> => <<"rsd">>,
  <<"application/vnd.crick.clicker.keyboard">> => <<"clkk">>,
  <<"text/troff">> => <<"tr">>,<<"application/rdf+xml">> => <<"rdf">>,
  <<"image/vnd.dxf">> => <<"dxf">>,
  <<"application/vnd.fujitsu.oasys3">> => <<"oa3">>,
  <<"application/vnd.nokia.n-gage.symbian.install">> => <<"n-gage">>,
  <<"application/patch-ops-error+xml">> => <<"xer">>,
  <<"application/vnd.ms-lrm">> => <<"lrm">>,
  <<"application/vnd.apple.installer+xml">> => <<"mpkg">>,
  <<"application/xml-dtd">> => <<"dtd">>,
  <<"application/vnd.proteus.magazine">> => <<"mgz">>,
  <<"image/x-freehand">> => <<"fhc">>,<<"application/mp21">> => <<"mp21">>,
  <<"application/x-msmetafile">> => <<"wmz">>,
  <<"application/pskc+xml">> => <<"pskcxml">>,
  <<"application/x-debian-package">> => <<"udeb">>,
  <<"application/vnd.yamaha.hv-script">> => <<"hvs">>,
  <<"application/vnd.cosmocaller">> => <<"cmc">>,
  <<"application/vnd.acucobol">> => <<"acu">>,
  <<"application/vnd.micrografx.flo">> => <<"flo">>,
  <<"application/vnd.realvnc.bed">> => <<"bed">>,
  <<"application/vnd.oma.dd2+xml">> => <<"dd2">>,
  <<"application/vnd.mobius.daf">> => <<"daf">>,
  <<"application/vnd.shana.informed.package">> => <<"ipk">>,
  <<"image/tiff">> => <<"tiff">>,
  <<"application/atomcat+xml">> => <<"atomcat">>,
  <<"application/x-netcdf">> => <<"nc">>,
  <<"application/ssml+xml">> => <<"ssml">>,<<"application/x-sh">> => <<"sh">>,
  <<"application/x-sql">> => <<"sql">>,
  <<"application/x-ms-wmz">> => <<"wmz">>,
  <<"application/vnd.nokia.radio-presets">> => <<"rpss">>,
  <<"application/vnd.adobe.fxp">> => <<"fxpl">>,
  <<"application/x-xliff+xml">> => <<"xlf">>,
  <<"application/vnd.webturbo">> => <<"wtb">>,
  <<"application/vnd.ms-excel">> => <<"xlw">>,
  <<"application/vnd.visio">> => <<"vsw">>,<<"video/vnd.fvt">> => <<"fvt">>,
  <<"model/vnd.gtw">> => <<"gtw">>,<<"image/gif">> => <<"gif">>,
  <<"text/vnd.in3d.3dml">> => <<"3dml">>,
  <<"application/pkcs7-mime">> => <<"p7m">>,
  <<"application/vnd.crick.clicker">> => <<"clkx">>,
  <<"image/x-icon">> => <<"ico">>,<<"image/vnd.fpx">> => <<"fpx">>,
  <<"application/vnd.ms-cab-compressed">> => <<"cab">>,
  <<"application/vnd.hp-hpid">> => <<"hpid">>,
  <<"application/x-msaccess">> => <<"mdb">>,<<"text/x-asm">> => <<"s">>,
  <<"application/mets+xml">> => <<"mets">>,
  <<"application/vnd.uoml+xml">> => <<"uoml">>,
  <<"application/vnd.sun.xml.calc.template">> => <<"stc">>,
  <<"application/mp4">> => <<"mp4s">>,<<"text/html">> => <<"html">>,
  <<"application/vnd.groove-tool-message">> => <<"gtm">>,
  <<"application/mediaservercontrol+xml">> => <<"mscml">>,
  <<"video/vnd.uvvu.mp4">> => <<"uvvu">>,
  <<"application/java-serialized-object">> => <<"ser">>,
  <<"application/vnd.irepository.package+xml">> => <<"irp">>,
  <<"application/x-font-ghostscript">> => <<"gsf">>,
  <<"application/vnd.ufdl">> => <<"ufdl">>,
  <<"application/atomsvc+xml">> => <<"atomsvc">>,
  <<"application/applixware">> => <<"aw">>,
  <<"application/x-subrip">> => <<"srt">>,
  <<"video/vnd.dece.sd">> => <<"uvvs">>,
  <<"application/vnd.intercon.formnet">> => <<"xpx">>,
  <<"application/vnd.grafeq">> => <<"gqs">>,
  <<"application/vnd.simtech-mindmapper">> => <<"twds">>,
  <<"application/mac-binhex40">> => <<"hqx">>,
  <<"video/vnd.ms-playready.media.pyv">> => <<"pyv">>,
  <<"model/vrml">> => <<"wrl">>,<<"video/x-ms-vob">> => <<"vob">>,
  <<"application/vnd.dolby.mlp">> => <<"mlp">>,
  <<"text/vnd.in3d.spot">> => <<"spot">>,
  <<"application/vnd.noblenet-sealer">> => <<"nns">>,
  <<"audio/x-matroska">> => <<"mka">>,<<"application/x-gtar">> => <<"gtar">>,
  <<"application/vnd.cups-ppd">> => <<"ppd">>,
  <<"video/x-msvideo">> => <<"avi">>,<<"audio/vnd.dts.hd">> => <<"dtshd">>,
  <<"application/vnd.handheld-entertainment+xml">> => <<"zmm">>,
  <<"application/x-sv4crc">> => <<"sv4crc">>,
  <<"application/oxps">> => <<"oxps">>,
  <<"application/x-texinfo">> => <<"texinfo">>,
  <<"application/vnd.wap.wmlscriptc">> => <<"wmlsc">>,
  <<"application/x-blorb">> => <<"blorb">>,
  <<"application/x-director">> => <<"w3d">>,
  <<"application/vnd.businessobjects">> => <<"rep">>,
  <<"application/vnd.oasis.opendocument.formula">> => <<"odf">>,
  <<"chemical/x-cml">> => <<"cml">>,<<"application/vnd.is-xpr">> => <<"xpr">>,
  <<"application/vnd.intu.qbo">> => <<"qbo">>,
  <<"application/vnd.adobe.xfdf">> => <<"xfdf">>,
  <<"audio/x-pn-realaudio-plugin">> => <<"rmp">>,
  <<"application/xml">> => <<"xsl">>,
  <<"application/vnd.adobe.xdp+xml">> => <<"xdp">>,
  <<"application/x-bzip">> => <<"bz">>,<<"chemical/x-cmdf">> => <<"cmdf">>,
  <<"application/x-bzip2">> => <<"bz2">>,<<"image/webp">> => <<"webp">>,
  <<"text/calendar">> => <<"ifb">>,
  <<"application/vnd.stardivision.writer">> => <<"vor">>,
  <<"application/vnd.anser-web-certificate-issue-initiation">> => <<"cii">>,
  <<"application/vnd.immervision-ivu">> => <<"ivu">>,
  <<"application/vnd.jam">> => <<"jam">>,
  <<"application/vnd.fluxtime.clip">> => <<"ftc">>,
  <<"application/vnd.kde.karbon">> => <<"karbon">>,
  <<"application/vnd.epson.salt">> => <<"slt">>,
  <<"application/vnd.insors.igm">> => <<"igm">>,
  <<"application/vnd.geoplan">> => <<"g2w">>,
  <<"image/x-xbitmap">> => <<"xbm">>,<<"application/vnd.palm">> => <<"pqa">>,
  <<"audio/mp4">> => <<"mp4a">>,<<"application/x-shar">> => <<"shar">>,
  <<"application/vnd.noblenet-web">> => <<"nnw">>,
  <<"application/x-mspublisher">> => <<"pub">>,
  <<"application/rss+xml">> => <<"rss">>,
  <<"model/x3d+binary">> => <<"x3dbz">>,
  <<"application/vnd.mcd">> => <<"mcd">>,
  <<"application/cdmi-object">> => <<"cdmio">>,
  <<"application/vnd.fujitsu.oasys">> => <<"oas">>,
  <<"application/vnd.oasis.opendocument.presentation">> => <<"odp">>,
  <<"font/woff2">> => <<"woff2">>,<<"application/x-font-snf">> => <<"snf">>,
  <<"application/vnd.powerbuilder6">> => <<"pbd">>,
  <<"application/vnd.sun.xml.writer.global">> => <<"sxg">>,
  <<"application/x-install-instructions">> => <<"install">>,
  <<"application/reginfo+xml">> => <<"rif">>,
  <<"application/vnd.hp-hpgl">> => <<"hpgl">>,
  <<"text/vnd.wap.wmlscript">> => <<"wmls">>,
  <<"video/vnd.dece.video">> => <<"uvvv">>,<<"audio/x-caf">> => <<"caf">>,
  <<"application/vnd.pmi.widget">> => <<"wg">>,
  <<"application/scvp-vp-request">> => <<"spq">>,
  <<"application/x-research-info-systems">> => <<"ris">>,
  <<"application/vnd.syncml.dm+wbxml">> => <<"bdm">>,
  <<"application/x-cfs-compressed">> => <<"cfs">>,
  <<"audio/vnd.dra">> => <<"dra">>,
  <<"application/vnd.pvi.ptid1">> => <<"ptid">>,
  <<"application/vnd.oasis.opendocument.chart-template">> => <<"otc">>,
  <<"application/sparql-results+xml">> => <<"srx">>,
  <<"audio/x-wav">> => <<"wav">>,<<"audio/ogg">> => <<"spx">>,
  <<"application/vnd.ms-excel.addin.macroenabled.12">> => <<"xlam">>,
  <<"text/vnd.curl.dcurl">> => <<"dcurl">>,
  <<"application/vnd.accpac.simply.imp">> => <<"imp">>,
  <<"application/vnd.denovo.fcselayout-link">> => <<"fe_launch">>,
  <<"text/plain">> => <<"txt">>,
  <<"application/vnd.kde.kontour">> => <<"kon">>,
  <<"application/xproc+xml">> => <<"xpl">>,
  <<"application/vnd.recordare.musicxml">> => <<"mxl">>,
  <<"application/vnd.openxmlformats-officedocument.presentationml.slideshow">> =>
      <<"ppsx">>,
  <<"text/vnd.dvb.subtitle">> => <<"sub">>,<<"audio/vnd.dts">> => <<"dts">>,
  <<"application/x-conference">> => <<"nsc">>,
  <<"application/set-payment-initiation">> => <<"setpay">>,
  <<"application/vnd.ctc-posml">> => <<"pml">>,
  <<"application/vnd.cluetrust.cartomobile-config-pkg">> => <<"c11amz">>,
  <<"application/vnd.ezpix-package">> => <<"ez3">>,
  <<"application/vnd.syncml.dm+xml">> => <<"xdm">>,
  <<"application/vnd.ms-artgalry">> => <<"cil">>,
  <<"application/oda">> => <<"oda">>,
  <<"application/vnd.yamaha.openscoreformat">> => <<"osf">>,
  <<"application/vnd.dart">> => <<"dart">>,
  <<"application/vnd.oasis.opendocument.image-template">> => <<"oti">>,
  <<"application/vnd.clonk.c4group">> => <<"c4u">>,
  <<"application/x-java-jnlp-file">> => <<"jnlp">>,
  <<"application/vnd.dpgraph">> => <<"dpg">>,
  <<"image/vnd.xiff">> => <<"xif">>,
  <<"application/vnd.solent.sdkm+xml">> => <<"sdkm">>,
  <<"application/vnd.ms-wpl">> => <<"wpl">>,
  <<"application/vnd.adobe.formscentral.fcdt">> => <<"fcdt">>,
  <<"application/vnd.3m.post-it-notes">> => <<"pwn">>,
  <<"image/x-cmx">> => <<"cmx">>,
  <<"text/vnd.sun.j2me.app-descriptor">> => <<"jad">>,
  <<"application/vnd.kidspiration">> => <<"kia">>,
  <<"application/ecmascript">> => <<"ecma">>,
  <<"application/x-pkcs7-certificates">> => <<"spc">>,
  <<"application/x-ace-compressed">> => <<"ace">>,
  <<"application/dssc+der">> => <<"dssc">>,
  <<"application/vnd.groove-help">> => <<"ghf">>,
  <<"application/cu-seeme">> => <<"cu">>,
  <<"application/vnd.shana.informed.formdata">> => <<"ifm">>,
  <<"application/vnd.semd">> => <<"semd">>,
  <<"application/x-mie">> => <<"mie">>,
  <<"application/pgp-signature">> => <<"sig">>,
  <<"image/x-mrsid-image">> => <<"sid">>,
  <<"application/x-ms-application">> => <<"application">>,
  <<"application/vnd.americandynamics.acc">> => <<"acc">>,
  <<"application/rpki-roa">> => <<"roa">>,
  <<"application/vnd.symbian.install">> => <<"sisx">>,
  <<"application/vnd.ibm.minipay">> => <<"mpy">>,
  <<"application/vnd.oasis.opendocument.chart">> => <<"odc">>,
  <<"application/vnd.pawaafile">> => <<"paw">>,
  <<"application/srgs+xml">> => <<"grxml">>,
  <<"application/vnd.ms-excel.sheet.macroenabled.12">> => <<"xlsm">>,
  <<"application/x-tar">> => <<"tar">>,
  <<"application/x-msschedule">> => <<"scd">>,
  <<"application/x-tex">> => <<"tex">>,
  <<"application/vnd.hbci">> => <<"hbci">>,
  <<"application/atom+xml">> => <<"atom">>,
  <<"image/vnd.net-fpx">> => <<"npx">>,
  <<"application/vnd.llamagraphics.life-balance.desktop">> => <<"lbd">>,
  <<"application/dssc+xml">> => <<"xdssc">>,
  <<"application/x-mscardfile">> => <<"crd">>,
  <<"application/x-msmoney">> => <<"mny">>,
  <<"application/vnd.aristanetworks.swi">> => <<"swi">>,
  <<"application/vnd.pg.format">> => <<"str">>,
  <<"text/tab-separated-values">> => <<"tsv">>,
  <<"application/vnd.kde.kword">> => <<"kwt">>,
  <<"application/x-bcpio">> => <<"bcpio">>,
  <<"application/vnd.fdf">> => <<"fdf">>,
  <<"application/x-silverlight-app">> => <<"xap">>,
  <<"application/xenc+xml">> => <<"xenc">>,<<"application/sdp">> => <<"sdp">>,
  <<"application/metalink4+xml">> => <<"meta4">>,
  <<"chemical/x-cif">> => <<"cif">>,<<"audio/vnd.rip">> => <<"rip">>,
  <<"application/vnd.yamaha.openscoreformat.osfpvg+xml">> => <<"osfpvg">>,
  <<"video/vnd.dece.mobile">> => <<"uvvm">>,<<"video/h263">> => <<"h263">>,
  <<"application/x-ms-shortcut">> => <<"lnk">>,
  <<"application/vnd.amiga.ami">> => <<"ami">>,
  <<"application/vnd.macports.portpkg">> => <<"portpkg">>,
  <<"application/json">> => <<"json">>,
  <<"application/vnd.osgeo.mapguide.package">> => <<"mgp">>,
  <<"application/pgp-encrypted">> => <<"pgp">>,
  <<"application/vnd.wordperfect">> => <<"wpd">>,
  <<"application/vnd.dece.ttml+xml">> => <<"uvvt">>,
  <<"application/vnd.ms-word.document.macroenabled.12">> => <<"docm">>,
  <<"application/vnd.amazon.ebook">> => <<"azw">>,
  <<"text/sgml">> => <<"sgml">>,<<"font/collection">> => <<"ttc">>,
  <<"application/vnd.mfer">> => <<"mwf">>,
  <<"application/vnd.mif">> => <<"mif">>,
  <<"application/shf+xml">> => <<"shf">>,
  <<"application/vnd.3gpp.pic-bw-large">> => <<"plb">>,
  <<"text/turtle">> => <<"ttl">>,
  <<"application/vnd.kde.kchart">> => <<"chrt">>,
  <<"application/vnd.eszigno3+xml">> => <<"et3">>,
  <<"application/vnd.3gpp.pic-bw-var">> => <<"pvb">>,
  <<"application/vnd.nokia.radio-preset">> => <<"rpst">>,
  <<"application/javascript">> => <<"js">>,
  <<"application/vnd.oasis.opendocument.graphics-template">> => <<"otg">>,
  <<"model/vnd.collada+xml">> => <<"dae">>,
  <<"application/vnd.umajin">> => <<"umj">>,
  <<"application/docbook+xml">> => <<"dbk">>,
  <<"application/vnd.trueapp">> => <<"tra">>,
  <<"application/vnd.sun.xml.writer.template">> => <<"stw">>,
  <<"application/x-dgc-compressed">> => <<"dgc">>,
  <<"application/vnd.rn-realmedia-vbr">> => <<"rmvb">>,
  <<"application/hyperstudio">> => <<"stk">>,
  <<"application/vnd.stardivision.draw">> => <<"sda">>,
  <<"image/vnd.dece.graphic">> => <<"uvvi">>,
  <<"application/pdf">> => <<"pdf">>,
  <<"audio/vnd.nuera.ecelp7470">> => <<"ecelp7470">>,
  <<"text/vnd.graphviz">> => <<"gv">>,<<"text/csv">> => <<"csv">>,
  <<"text/x-java-source">> => <<"java">>,
  <<"application/sparql-query">> => <<"rq">>,
  <<"application/vnd.gmx">> => <<"gmx">>,
  <<"application/vnd.tao.intent-module-archive">> => <<"tao">>,
  <<"application/vnd.fsc.weblaunch">> => <<"fsc">>,
  <<"application/emma+xml">> => <<"emma">>,
  <<"application/x-msmediaview">> => <<"mvb">>,
  <<"video/x-ms-wmv">> => <<"wmv">>,
  <<"application/vnd.ms-powerpoint.addin.macroenabled.12">> => <<"ppam">>,
  <<"application/vnd.sun.xml.writer">> => <<"sxw">>,
  <<"application/gml+xml">> => <<"gml">>,<<"image/vnd.dwg">> => <<"dwg">>,
  <<"video/vnd.mpegurl">> => <<"mxu">>,<<"image/vnd.ms-modi">> => <<"mdi">>,
  <<"x-conference/x-cooltalk">> => <<"ice">>,
  <<"message/rfc822">> => <<"mime">>,
  <<"application/vnd.oasis.opendocument.formula-template">> => <<"odft">>,
  <<"application/vnd.contact.cmsg">> => <<"cdbcmsg">>,
  <<"audio/adpcm">> => <<"adp">>,<<"audio/x-ms-wax">> => <<"wax">>,
  <<"application/vnd.ms-powerpoint.template.macroenabled.12">> => <<"potm">>,
  <<"application/vnd.lotus-approach">> => <<"apr">>,
  <<"application/sbml+xml">> => <<"sbml">>,
  <<"application/vnd.dreamfactory">> => <<"dfac">>,
  <<"application/vnd.fujixerox.ddd">> => <<"ddd">>,
  <<"application/vnd.geospace">> => <<"g3w">>,
  <<"application/mathematica">> => <<"nb">>,
  <<"application/vnd.oasis.opendocument.presentation-template">> => <<"otp">>,
  <<"application/xcap-diff+xml">> => <<"xdf">>,
  <<"image/svg+xml">> => <<"svgz">>,<<"image/x-rgb">> => <<"rgb">>,
  <<"application/vnd.oasis.opendocument.text-template">> => <<"ott">>,
  <<"application/vnd.mfmp">> => <<"mfm">>,<<"image/x-xpixmap">> => <<"xpm">>,
  <<"application/vnd.ms-pki.stl">> => <<"stl">>,
  <<"application/vnd.bmi">> => <<"bmi">>,
  <<"application/vnd.adobe.air-application-installer-package+zip">> =>
      <<"air">>,
  <<"application/vnd.ms-works">> => <<"wps">>,
  <<"application/x-t3vm-image">> => <<"t3">>,
  <<"application/vnd.rim.cod">> => <<"cod">>,<<"video/mp4">> => <<"mpg4">>,
  <<"application/xslt+xml">> => <<"xslt">>,<<"image/bmp">> => <<"bmp">>,
  <<"application/x-authorware-bin">> => <<"x32">>,
  <<"application/vnd.kahootz">> => <<"ktz">>,
  <<"application/pkcs8">> => <<"p8">>,
  <<"application/x-msterminal">> => <<"trm">>,
  <<"text/x-setext">> => <<"etx">>,<<"application/vnd.nitf">> => <<"ntf">>,
  <<"application/vnd.stepmania.stepchart">> => <<"sm">>,
  <<"application/x-glulx">> => <<"ulx">>,
  <<"image/vnd.fujixerox.edmics-rlc">> => <<"rlc">>,
  <<"application/x-font-linux-psf">> => <<"psf">>,
  <<"application/x-ustar">> => <<"ustar">>,
  <<"video/x-sgi-movie">> => <<"movie">>,
  <<"application/x-gnumeric">> => <<"gnumeric">>,
  <<"application/x-stuffitx">> => <<"sitx">>,
  <<"text/x-vcalendar">> => <<"vcs">>,
  <<"application/cdmi-container">> => <<"cdmic">>,
  <<"audio/x-aiff">> => <<"aiff">>,<<"application/vnd.wt.stf">> => <<"stf">>,
  <<"application/vnd.mobius.msl">> => <<"msl">>,
  <<"application/vnd.musician">> => <<"mus">>,
  <<"application/x-futuresplash">> => <<"spl">>,
  <<"application/vnd.shana.informed.formtemplate">> => <<"itp">>,
  <<"video/x-ms-wm">> => <<"wm">>,
  <<"application/vnd.cloanto.rp9">> => <<"rp9">>,
  <<"application/vnd.sun.xml.math">> => <<"sxm">>,
  <<"application/vnd.criticaltools.wbs+xml">> => <<"wbs">>,
  <<"application/vnd.anser-web-funds-transfer-initiation">> => <<"fti">>,
  <<"application/vnd.xfdl">> => <<"xfdl">>,
  <<"application/x-iso9660-image">> => <<"iso">>,
  <<"application/oebps-package+xml">> => <<"opf">>,
  <<"text/x-fortran">> => <<"for">>,
  <<"application/vnd.mozilla.xul+xml">> => <<"xul">>,
  <<"application/x-xpinstall">> => <<"xpi">>,
  <<"model/x3d+vrml">> => <<"x3dvz">>,<<"text/x-opml">> => <<"opml">>,
  <<"video/quicktime">> => <<"qt">>,
  <<"application/vnd.shana.informed.interchange">> => <<"iif">>,
  <<"application/vnd.openxmlformats-officedocument.presentationml.slide">> =>
      <<"sldx">>,
  <<"application/x-tgif">> => <<"obj">>,
  <<"application/vnd.ms-powerpoint.slide.macroenabled.12">> => <<"sldm">>,
  <<"application/inkml+xml">> => <<"inkml">>,
  <<"application/tei+xml">> => <<"teicorpus">>,
  <<"application/x-wais-source">> => <<"src">>,
  <<"application/vnd.fuzzysheet">> => <<"fzs">>,
  <<"application/x-authorware-map">> => <<"aam">>,
  <<"application/vnd.intu.qfx">> => <<"qfx">>,
  <<"application/vnd.route66.link66+xml">> => <<"link66">>,
  <<"application/cdmi-queue">> => <<"cdmiq">>,<<"image/png">> => <<"png">>,
  <<"audio/vnd.digital-winds">> => <<"eol">>,
  <<"application/vnd.trid.tpt">> => <<"tpt">>,
  <<"application/vnd.3gpp2.tcap">> => <<"tcap">>,
  <<"application/yang">> => <<"yang">>,<<"application/x-chat">> => <<"chat">>,
  <<"application/vnd.yamaha.hv-voice">> => <<"hvp">>,
  <<"text/x-nfo">> => <<"nfo">>,<<"audio/x-ms-wma">> => <<"wma">>,
  <<"text/vnd.curl.scurl">> => <<"scurl">>,
  <<"application/vnd.sun.xml.calc">> => <<"sxc">>,
  <<"application/x-abiword">> => <<"abw">>,
  <<"application/x-sv4cpio">> => <<"sv4cpio">>,
  <<"application/omdoc+xml">> => <<"omdoc">>,
  <<"application/msword">> => <<"dot">>,
  <<"application/vnd.novadigm.ext">> => <<"ext">>,
  <<"application/x-stuffit">> => <<"sit">>,<<"video/jpm">> => <<"jpm">>,
  <<"application/vnd.fujitsu.oasysgp">> => <<"fg5">>,
  <<"application/vnd.yamaha.smaf-audio">> => <<"saf">>,
  <<"application/vnd.tmobile-livetv">> => <<"tmo">>,
  <<"application/vnd.mynfc">> => <<"taglet">>,
  <<"application/xaml+xml">> => <<"xaml">>,
  <<"application/smil+xml">> => <<"smil">>,<<"audio/x-aac">> => <<"aac">>,
  <<"application/pkcs7-signature">> => <<"p7s">>,
  <<"image/x-portable-graymap">> => <<"pgm">>,
  <<"application/lost+xml">> => <<"lostxml">>,
  <<"application/vnd.kde.kpresenter">> => <<"kpt">>,
  <<"application/vnd.mophun.certificate">> => <<"mpc">>,
  <<"application/xv+xml">> => <<"xvml">>,
  <<"application/x-shockwave-flash">> => <<"swf">>,
  <<"application/scvp-vp-response">> => <<"spp">>,
  <<"application/vnd.openxmlformats-officedocument.spreadsheetml.template">> =>
      <<"xltx">>,
  <<"application/x-mswrite">> => <<"wri">>,
  <<"application/x-chess-pgn">> => <<"pgn">>,
  <<"application/vnd.jcp.javame.midlet-rms">> => <<"rms">>,
  <<"application/x-dtbncx+xml">> => <<"ncx">>,
  <<"application/vnd.astraea-software.iota">> => <<"iota">>,
  <<"application/x-nzb">> => <<"nzb">>,<<"chemical/x-xyz">> => <<"xyz">>,
  <<"audio/x-mpegurl">> => <<"m3u">>,
  <<"application/vnd.epson.ssf">> => <<"ssf">>,
  <<"application/x-gramps-xml">> => <<"gramps">>,
  <<"application/vnd.epson.quickanime">> => <<"qam">>,
  <<"application/set-registration-initiation">> => <<"setreg">>,
  <<"application/vnd.spotfire.dxp">> => <<"dxp">>,
  <<"application/vnd.oasis.opendocument.spreadsheet">> => <<"ods">>,
  <<"application/vnd.visionary">> => <<"vis">>,
  <<"audio/vnd.ms-playready.media.pya">> => <<"pya">>,
  <<"application/vnd.audiograph">> => <<"aep">>,
  <<"application/x-rar-compressed">> => <<"rar">>,
  <<"application/vnd.kde.kivio">> => <<"flw">>,
  <<"text/vnd.curl">> => <<"curl">>,
  <<"application/vnd.mediastation.cdkey">> => <<"cdkey">>,
  <<"application/vnd.dece.unspecified">> => <<"uvx">>,
  <<"application/vnd.ms-powerpoint.presentation.macroenabled.12">> =>
      <<"pptm">>,
  <<"application/vnd.groove-injector">> => <<"grv">>,
  <<"application/zip">> => <<"zip">>,
  <<"application/vnd.immervision-ivp">> => <<"ivp">>,
  <<"application/exi">> => <<"exi">>,<<"application/x-freearc">> => <<"arc">>,
  <<"application/wsdl+xml">> => <<"wsdl">>,<<"application/mxf">> => <<"mxf">>,
  <<"application/vnd.ibm.modcap">> => <<"listafp">>,
  <<"application/vnd.ms-xpsdocument">> => <<"xps">>,
  <<"image/vnd.fst">> => <<"fst">>,<<"image/ief">> => <<"ief">>,
  <<"application/vnd.vcx">> => <<"vcx">>,<<"model/iges">> => <<"igs">>,
  <<"application/cdmi-capability">> => <<"cdmia">>,
  <<"model/vnd.gdl">> => <<"gdl">>,<<"application/thraud+xml">> => <<"tfi">>,
  <<"application/xspf+xml">> => <<"xspf">>,<<"video/x-smv">> => <<"smv">>,
  <<"audio/mpeg">> => <<"mpga">>,<<"audio/xm">> => <<"xm">>,
  <<"application/vnd.rn-realmedia">> => <<"rm">>,
  <<"application/metalink+xml">> => <<"metalink">>,
  <<"text/x-uuencode">> => <<"uu">>,<<"application/x-msbinder">> => <<"obd">>,
  <<"application/vnd.uiq.theme">> => <<"utz">>,
  <<"application/vnd.cinderella">> => <<"cdy">>,
  <<"application/x-authorware-seg">> => <<"aas">>,
  <<"application/vnd.curl.car">> => <<"car">>,
  <<"application/x-msclip">> => <<"clp">>,
  <<"application/x-envoy">> => <<"evy">>,
  <<"application/vnd.dvb.service">> => <<"svc">>,
  <<"application/vnd.sema">> => <<"sema">>,
  <<"application/srgs">> => <<"gram">>,
  <<"application/timestamped-data">> => <<"tsd">>,
  <<"application/vnd.fujitsu.oasys2">> => <<"oa2">>,
  <<"application/vnd.triscape.mxs">> => <<"mxs">>,
  <<"application/vnd.picsel">> => <<"efif">>,
  <<"application/x-mobipocket-ebook">> => <<"prc">>,
  <<"application/x-zmachine">> => <<"z8">>,<<"audio/basic">> => <<"snd">>,
  <<"application/vnd.yellowriver-custom-menu">> => <<"cmp">>,
  <<"application/cdmi-domain">> => <<"cdmid">>,<<"image/sgi">> => <<"sgi">>,
  <<"text/x-vcard">> => <<"vcf">>,<<"application/java-vm">> => <<"class">>,
  <<"font/ttf">> => <<"ttf">>,<<"image/x-portable-bitmap">> => <<"pbm">>,
  <<"application/postscript">> => <<"ps">>,
  <<"application/rls-services+xml">> => <<"rs">>,
  <<"application/vnd.dna">> => <<"dna">>,
  <<"application/rpki-manifest">> => <<"mft">>,<<"video/mpeg">> => <<"mpg">>,
  <<"text/css">> => <<"css">>,<<"application/vnd.hal+xml">> => <<"hal">>,
  <<"audio/vnd.dece.audio">> => <<"uvva">>,
  <<"application/vnd.ezpix-album">> => <<"ez2">>,
  <<"application/vnd.smart.teacher">> => <<"teacher">>,
  <<"application/java-archive">> => <<"jar">>,
  <<"application/vnd.oasis.opendocument.spreadsheet-template">> => <<"ots">>,
  <<"application/vnd.pg.osasli">> => <<"ei6">>,
  <<"image/vnd.djvu">> => <<"djvu">>,
  <<"application/vnd.geometry-explorer">> => <<"gre">>,
  <<"application/vnd.mobius.plc">> => <<"plc">>,
  <<"audio/vnd.nuera.ecelp9600">> => <<"ecelp9600">>,
  <<"text/vnd.fly">> => <<"fly">>,
  <<"application/vnd.groove-identity-message">> => <<"gim">>,
  <<"application/vnd.medcalcdata">> => <<"mc1">>,
  <<"application/vnd.kde.kformula">> => <<"kfo">>,
  <<"application/vnd.ms-fontobject">> => <<"eot">>,
  <<"model/mesh">> => <<"silo">>,<<"audio/vnd.lucent.voice">> => <<"lvp">>,
  <<"application/scvp-cv-response">> => <<"scs">>,
  <<"application/vnd.iccprofile">> => <<"icm">>,
  <<"video/x-mng">> => <<"mng">>,<<"application/marc">> => <<"mrc">>,
  <<"image/vnd.wap.wbmp">> => <<"wbmp">>,
  <<"text/cache-manifest">> => <<"appcache">>,
  <<"application/scvp-cv-request">> => <<"scq">>,
  <<"application/vnd.oasis.opendocument.text">> => <<"odt">>,
  <<"application/x-cbr">> => <<"cbz">>,
  <<"application/pkix-cert">> => <<"cer">>,
  <<"application/vnd.syncml+xml">> => <<"xsm">>,
  <<"application/x-xfig">> => <<"fig">>,
  <<"application/vnd.ms-excel.template.macroenabled.12">> => <<"xltm">>,
  <<"application/vnd.llamagraphics.life-balance.exchange+xml">> => <<"lbe">>,
  <<"application/x-doom">> => <<"wad">>,
  <<"application/vnd.olpc-sugar">> => <<"xo">>,
  <<"application/vnd.google-earth.kml+xml">> => <<"kml">>,
  <<"application/vnd.geonext">> => <<"gxt">>,
  <<"application/vnd.frogans.ltf">> => <<"ltf">>,
  <<"application/vnd.recordare.musicxml+xml">> => <<"musicxml">>,
  <<"application/x-font-bdf">> => <<"bdf">>,
  <<"image/vnd.ms-photo">> => <<"wdp">>,
  <<"application/onenote">> => <<"onetoc2">>,
  <<"video/vnd.dece.hd">> => <<"uvvh">>,<<"video/h264">> => <<"h264">>,
  <<"application/font-tdpfr">> => <<"pfr">>,
  <<"image/x-portable-pixmap">> => <<"ppm">>,
  <<"application/vnd.unity">> => <<"unityweb">>,
  <<"application/octet-stream">> => <<"so">>,
  <<"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet">> =>
      <<"xlsx">>,
  <<"application/vnd.zzazz.deck+xml">> => <<"zaz">>,
  <<"application/resource-lists+xml">> => <<"rl">>,
  <<"image/x-pcx">> => <<"pcx">>,<<"image/jpeg">> => <<"jpg">>,
  <<"application/vnd.mobius.dis">> => <<"dis">>,
  <<"application/vnd.crick.clicker.template">> => <<"clkt">>,
  <<"application/vnd.chemdraw+xml">> => <<"cdxml">>,
  <<"application/vnd.previewsystems.box">> => <<"box">>,
  <<"application/rtf">> => <<"rtf">>,
  <<"application/vnd.hp-hps">> => <<"hps">>,
  <<"application/x-cdlink">> => <<"vcd">>,
  <<"application/vnd.airzip.filesecure.azs">> => <<"azs">>,
  <<"application/vnd.framemaker">> => <<"maker">>,
  <<"model/vnd.mts">> => <<"mts">>,<<"chemical/x-cdx">> => <<"cdx">>,
  <<"application/gxf">> => <<"gxf">>,
  <<"application/vnd.chipnuts.karaoke-mmd">> => <<"mmd">>,
  <<"audio/s3m">> => <<"s3m">>,
  <<"application/vnd.mophun.application">> => <<"mpn">>,
  <<"application/ipfix">> => <<"ipfix">>,
  <<"application/vnd.koan">> => <<"skt">>,
  <<"application/vnd.frogans.fnc">> => <<"fnc">>,
  <<"application/mac-compactpro">> => <<"cpt">>,
  <<"image/vnd.adobe.photoshop">> => <<"psd">>,
  <<"application/vnd.kodak-descriptor">> => <<"sse">>,
  <<"application/vnd.openxmlformats-officedocument.presentationml.template">> =>
      <<"potx">>,
  <<"application/vnd.mobius.mqy">> => <<"mqy">>,
  <<"application/x-pkcs12">> => <<"pfx">>,
  <<"application/vnd.lotus-freelance">> => <<"pre">>,
  <<"video/x-fli">> => <<"fli">>,
  <<"application/vnd.openofficeorg.extension">> => <<"oxt">>,
  <<"application/resource-lists-diff+xml">> => <<"rld">>,
  <<"application/vnd.semf">> => <<"semf">>,<<"image/x-pict">> => <<"pic">>,
  <<"application/ccxml+xml">> => <<"ccxml">>,<<"video/x-flv">> => <<"flv">>,
  <<"application/vnd.micrografx.igx">> => <<"igx">>,
  <<"image/x-tga">> => <<"tga">>,<<"application/vnd.jisp">> => <<"jisp">>,
  <<"application/vnd.ibm.rights-management">> => <<"irm">>,
  <<"application/x-cpio">> => <<"cpio">>,<<"font/woff">> => <<"woff">>,
  <<"application/x-bittorrent">> => <<"torrent">>,
  <<"text/vnd.wap.wml">> => <<"wml">>,
  <<"application/vnd.las.las+xml">> => <<"lasxml">>,
  <<"image/prs.btif">> => <<"btif">>,
  <<"application/vnd.acucorp">> => <<"atc">>,
  <<"application/vnd.noblenet-directory">> => <<"nnd">>,
  <<"application/x-tcl">> => <<"tcl">>,
  <<"application/vnd.hp-pclxl">> => <<"pclxl">>,
  <<"application/vnd.data-vision.rdz">> => <<"rdz">>,
  <<"application/x-xz">> => <<"xz">>,
  <<"application/vnd.oasis.opendocument.graphics">> => <<"odg">>,
  <<"text/uri-list">> => <<"urls">>,
  <<"application/vnd.novadigm.edm">> => <<"edm">>,
  <<"model/vnd.dwf">> => <<"dwf">>,
  <<"application/x-lzh-compressed">> => <<"lzh">>,
  <<"application/vnd.ms-powerpoint.slideshow.macroenabled.12">> => <<"ppsm">>,
  <<"application/vnd.igloader">> => <<"igl">>,
  <<"image/x-cmu-raster">> => <<"ras">>,<<"audio/midi">> => <<"rmi">>,
  <<"application/mads+xml">> => <<"mads">>,
  <<"application/x-dtbook+xml">> => <<"dtb">>,
  <<"application/vnd.ds-keypoint">> => <<"kpxx">>,
  <<"application/vnd.intergeo">> => <<"i2g">>,
  <<"application/pkix-attr-cert">> => <<"ac">>,
  <<"application/vnd.apple.mpegurl">> => <<"m3u8">>,
  <<"application/vnd.fujitsu.oasysprs">> => <<"bh2">>,
  <<"application/vnd.openxmlformats-officedocument.presentationml.presentation">> =>
      <<"pptx">>,
  <<"application/vnd.rig.cryptonote">> => <<"cryptonote">>,
  <<"application/vnd.sun.xml.impress">> => <<"sxi">>,
  <<"application/vnd.wqd">> => <<"wqd">>,
  <<"application/pkcs10">> => <<"p10">>,
  <<"application/andrew-inset">> => <<"ez">>,<<"video/h261">> => <<"h261">>,
  <<"video/x-f4v">> => <<"f4v">>,<<"text/x-pascal">> => <<"pas">>,
  <<"application/vnd.ms-word.template.macroenabled.12">> => <<"dotm">>,
  <<"video/x-ms-asf">> => <<"asx">>,
  <<"application/vnd.android.package-archive">> => <<"apk">>,
  <<"application/vnd.hydrostatix.sof-data">> => <<"sfd-hdstx">>,
  <<"application/winhlp">> => <<"hlp">>,
  <<"application/vnd.isac.fcs">> => <<"fcs">>,<<"image/cgm">> => <<"cgm">>,
  <<"application/vnd.hhe.lesson-player">> => <<"les">>,
  <<"application/vnd.geogebra.tool">> => <<"ggt">>,
  <<"application/vnd.kinar">> => <<"knp">>,
  <<"application/x-gca-compressed">> => <<"gca">>,
  <<"application/vnd.sun.xml.impress.template">> => <<"sti">>,
  <<"application/jsonml+json">> => <<"jsonml">>,
  <<"image/vnd.fujixerox.edmics-mmr">> => <<"mmr">>,
  <<"application/xop+xml">> => <<"xop">>,
  <<"text/prs.lines.tag">> => <<"dsc">>,
  <<"application/vnd.lotus-1-2-3">> => <<"123">>,
  <<"video/x-m4v">> => <<"m4v">>,
  <<"application/vnd.kde.kspread">> => <<"ksp">>,
  <<"application/epub+zip">> => <<"epub">>,
  <<"application/vnd.ms-pki.seccat">> => <<"cat">>,
  <<"application/x-x509-ca-cert">> => <<"der">>,
  <<"application/vnd.blueice.multipass">> => <<"mpm">>,
  <<"application/yin+xml">> => <<"yin">>,
  <<"application/sru+xml">> => <<"sru">>,
  <<"application/vnd.wap.wbxml">> => <<"wbxml">>,
  <<"application/vnd.tcpdump.pcap">> => <<"pcap">>,
  <<"application/vnd.ms-ims">> => <<"ims">>,
  <<"application/pics-rules">> => <<"prf">>,
  <<"application/vnd.osgi.subsystem">> => <<"esa">>,
  <<"application/vnd.fujixerox.docuworks.binder">> => <<"xbd">>,
  <<"application/vnd.dece.data">> => <<"uvvf">>,
  <<"application/x-apple-diskimage">> => <<"dmg">>,
  <<"application/vnd.dvb.ait">> => <<"ait">>,
  <<"application/x-hdf">> => <<"hdf">>,
  <<"application/vnd.sus-calendar">> => <<"susp">>,
  <<"video/ogg">> => <<"ogv">>,
  <<"application/vnd.nokia.n-gage.data">> => <<"ngdat">>,
  <<"audio/vnd.nuera.ecelp4800">> => <<"ecelp4800">>,
  <<"application/vnd.sailingtracker.track">> => <<"st">>,
  <<"application/x-csh">> => <<"csh">>,
  <<"application/vnd.lotus-wordpro">> => <<"lwp">>,
  <<"application/x-font-type1">> => <<"pfm">>,
  <<"video/x-ms-wmx">> => <<"wmx">>,
  <<"application/vnd.stepmania.package">> => <<"smzip">>,
  <<"application/x-eva">> => <<"eva">>,<<"image/x-3ds">> => <<"3ds">>,
  <<"application/vnd.ms-project">> => <<"mpt">>,
  <<"audio/webm">> => <<"weba">>,
  <<"application/vnd.fujixerox.docuworks">> => <<"xdw">>,
  <<"application/pls+xml">> => <<"pls">>,
  <<"application/vnd.openxmlformats-officedocument.wordprocessingml.document">> =>
      <<"docx">>,
  <<"video/x-matroska">> => <<"mkv">>,
  <<"application/vnd.3gpp.pic-bw-small">> => <<"psb">>,
  <<"application/vnd.hp-pcl">> => <<"pcl">>,
  <<"application/vnd.neurolanguage.nlu">> => <<"nlu">>,
  <<"application/x-ms-wmd">> => <<"wmd">>,
  <<"application/vnd.osgi.dp">> => <<"dp">>,<<"audio/x-flac">> => <<"flac">>,
  <<"application/vnd.cluetrust.cartomobile-config">> => <<"c11amc">>,
  <<"application/vnd.antix.game-component">> => <<"atx">>,
  <<"application/vnd.wap.wmlc">> => <<"wmlc">>,
  <<"text/vnd.fmi.flexstor">> => <<"flx">>,
  <<"application/mods+xml">> => <<"mods">>,
  <<"application/voicexml+xml">> => <<"vxml">>,
  <<"application/vnd.ms-htmlhelp">> => <<"chm">>,
  <<"video/webm">> => <<"webm">>,
  <<"application/vnd.yamaha.hv-dic">> => <<"hvd">>,
  <<"video/vnd.dece.pd">> => <<"uvvp">>,
  <<"application/vnd.vsf">> => <<"vsf">>,
  <<"image/x-portable-anymap">> => <<"pnm">>,
  <<"application/x-latex">> => <<"latex">>,
  <<"application/vnd.mobius.mbk">> => <<"mbk">>,
  <<"application/vnd.spotfire.sfs">> => <<"sfs">>,
  <<"application/mathml+xml">> => <<"mathml">>,<<"text/x-c">> => <<"hh">>,
  <<"image/x-xwindowdump">> => <<"xwd">>,
  <<"application/vnd.ecowin.chart">> => <<"mag">>,
  <<"text/x-sfv">> => <<"sfv">>,<<"text/richtext">> => <<"rtx">>,
  <<"image/g3fax">> => <<"g3">>,<<"application/vnd.claymore">> => <<"cla">>,
  <<"application/vnd.stardivision.writer-global">> => <<"sgl">>,
  <<"application/pkix-pkipath">> => <<"pkipath">>,
  <<"application/x-pkcs7-certreqresp">> => <<"p7r">>,
  <<"application/vnd.quark.quarkxpress">> => <<"qxt">>,
  <<"application/vnd.crick.clicker.wordbank">> => <<"clkw">>,
  <<"application/pkix-crl">> => <<"crl">>,<<"video/jpeg">> => <<"jpgv">>,
  <<"application/ogg">> => <<"ogx">>,
  <<"application/vnd.pocketlearn">> => <<"plf">>,
  <<"application/x-tex-tfm">> => <<"tfm">>,
  <<"application/vnd.dynageo">> => <<"geo">>,
  <<"application/vnd.oasis.opendocument.database">> => <<"odb">>,
  <<"application/gpx+xml">> => <<"gpx">>,
  <<"application/ssdl+xml">> => <<"ssdl">>,
  <<"application/vnd.kenameaapp">> => <<"htke">>,
  <<"application/x-msdownload">> => <<"msi">>,
  <<"application/xhtml+xml">> => <<"xhtml">>,
  <<"application/vnd.ibm.secure-container">> => <<"sc">>,
  <<"application/vnd.ahead.space">> => <<"ahead">>,
  <<"application/vnd.groove-tool-template">> => <<"tpl">>,
  <<"application/vnd.publishare-delta-tree">> => <<"qps">>,
  <<"application/vnd.stardivision.impress">> => <<"sdd">>,
  <<"image/vnd.fastbidsheet">> => <<"fbs">>,
  <<"application/vnd.flographit">> => <<"gph">>,
  <<"application/vnd.wolfram.player">> => <<"nbp">>,
  <<"image/vnd.dvb.subtitle">> => <<"sub">>,
  <<"application/vnd.ipunplugged.rcprofile">> => <<"rcprofile">>,
  <<"application/vnd.svd">> => <<"svd">>,<<"model/vnd.vtu">> => <<"vtu">>,
  <<"application/vnd.yamaha.smaf-phrase">> => <<"spf">>,
  <<"application/wspolicy+xml">> => <<"wspolicy">>,
  <<"application/vnd.mseq">> => <<"mseq">>,
  <<"application/vnd.xara">> => <<"xar">>,
  <<"application/widget">> => <<"wgt">>,
  <<"application/vnd.hp-jlyt">> => <<"jlt">>,<<"image/ktx">> => <<"ktx">>,
  <<"application/marcxml+xml">> => <<"mrcx">>,
  <<"audio/x-pn-realaudio">> => <<"ram">>,<<"video/x-ms-wvx">> => <<"wvx">>,
  <<"application/x-font-pcf">> => <<"pcf">>,<<"video/3gpp">> => <<"3gp">>,
  <<"application/mbox">> => <<"mbox">>,
  <<"application/vnd.fdsn.seed">> => <<"seed">>,
  <<"application/vnd.google-earth.kmz">> => <<"kmz">>,
  <<"application/x-ms-xbap">> => <<"xbap">>,
  <<"application/vnd.smaf">> => <<"mmf">>,<<"video/mj2">> => <<"mjp2">>,
  <<"application/vnd.lotus-screencam">> => <<"scm">>,
  <<"application/vnd.sun.xml.draw.template">> => <<"std">>,
  <<"application/vnd.sun.xml.draw">> => <<"sxd">>,
  <<"application/vnd.stardivision.calc">> => <<"sdc">>,
  <<"application/x-tads">> => <<"gam">>,<<"text/vcard">> => <<"vcard">>,
  <<"application/vnd.openxmlformats-officedocument.wordprocessingml.template">> =>
      <<"dotx">>,
  <<"application/x-7z-compressed">> => <<"7z">>,<<"font/otf">> => <<"otf">>,
  <<"application/vnd.lotus-organizer">> => <<"org">>,
  <<"application/vnd.airzip.filesecure.azf">> => <<"azf">>,
  <<"application/vnd.epson.msf">> => <<"msf">>,
  <<"application/relax-ng-compact-syntax">> => <<"rnc">>,
  <<"application/vnd.ms-powerpoint">> => <<"ppt">>,
  <<"application/vnd.geogebra.file">> => <<"ggb">>,
  <<"application/vnd.ms-excel.sheet.binary.macroenabled.12">> => <<"xlsb">>,
  <<"application/vnd.seemail">> => <<"see">>,
  <<"application/vnd.fdsn.mseed">> => <<"mseed">>,
  <<"application/vnd.oasis.opendocument.text-web">> => <<"oth">>,
  <<"application/vnd.mobius.txf">> => <<"txf">>,
  <<"application/vnd.commonspace">> => <<"csp">>,
  <<"application/vnd.oasis.opendocument.image">> => <<"odi">>,
  <<"application/vnd.accpac.simply.aso">> => <<"aso">>,
  <<"application/vnd.novadigm.edx">> => <<"edx">>,
  <<"application/vnd.oasis.opendocument.text-master">> => <<"odm">>,
  <<"application/vnd.stardivision.math">> => <<"smf">>,
  <<"application/x-dvi">> => <<"dvi">>,
  <<"application/rpki-ghostbusters">> => <<"gbr">>,
  <<"application/vnd.curl.pcurl">> => <<"pcurl">>,
  <<"application/vnd.enliven">> => <<"nml">>,
  <<"application/vnd.groove-account">> => <<"gac">>,
  <<"chemical/x-csml">> => <<"csml">>,<<"text/n3">> => <<"n3">>,
  <<"application/prs.cww">> => <<"cww">>,
  <<"application/vnd.dece.zip">> => <<"uvz">>,
  <<"video/vnd.vivo">> => <<"viv">>,<<"text/vnd.curl.mcurl">> => <<"mcurl">>,
  <<"application/vnd.muvee.style">> => <<"msty">>,
  <<"application/x-dtbresource+xml">> => <<"res">>,
  <<"application/vnd.groove-vcard">> => <<"vcg">>,
  <<"application/vnd.ms-officetheme">> => <<"thmx">>,
  <<"application/vnd.zul">> => <<"zirz">>,
  <<"application/vnd.crick.clicker.palette">> => <<"clkp">>,
  <<"audio/silk">> => <<"sil">>,<<"video/vnd.dvb.file">> => <<"dvb">>,
  <<"application/vnd.genomatix.tuxedo">> => <<"txd">>,
  <<"application/vnd.joost.joda-archive">> => <<"joda">>,
  <<"application/vnd.epson.esf">> => <<"esf">>,
  <<"application/davmount+xml">> => <<"davmount">>,
  <<"application/pkixcmp">> => <<"pki">>,<<"video/3gpp2">> => <<"3g2">>}).

ext(Mime) -> maps:get(Mime, ?MIMES, undefined).
mime(Ext) -> 
    {C1, C2, _} = cow_mimetypes:all(<<"a.", Ext/binary>>),
    list_to_binary([C1, "/", C2]).
